### ISSUE TITLE
Verify the existing failure test suite works for A/P and A/A setup after the changes in deployment config

### ISSUE THREAD

**Issue by kami619** [keycloak/keycloak-benchmark#924]
Smoke-test the scenarios below in the new Active/Active setup to ensure they execute properly.

```[tasklist]
### Tasks
- [x] Chaos test - kill-keycloak - works as expected
- [x] Chaos test - kill-infinispan - works as expected
- [x] Chaos test - kill-gossip-router - doesn't execute as expected
- [x] Failure & Recovery test - HEALTH_PROBE - wont work with Global Accelerator
- [x] Failure & Recovery test - KEYCLOAK_ROUTES - wont work with Global Accelerator
- [x] Failure & Recovery test - CLUSTER_FAIL - works with some non-blocking issues with the `kc-failover.sh` script.
- [x] Failure & Recovery test - GOSSIP_ROUTER_FAIL - works as expected
```

**Comment by kami619** [comment]
We need to add docs for the Kraken Chaos tests, as it needs an existing Kube config and context of the ISPN and Keycloak for the tests to start and need a Docker or Podman socket connection to pull the images.

**Comment by kami619** [comment]
There seems to be an issue with Kraken recognizing the pods which are coming back for gossip-router and fails with a timeout message. Need to debug this, at least some form of regression from the past.

```
[chaos:kraken-pod-scenarios] 2024-08-15 14:26:54,129 [INFO] Executing scenarios for iteration 0
[chaos:kraken-pod-scenarios] 2024-08-15 14:26:54,144 [INFO] scenario scenarios/pod_scenario.yaml
[chaos:kraken-pod-scenarios] 2024-08-15 14:26:55,532 [INFO] {
[chaos:kraken-pod-scenarios] 	"output_id": "success",
[chaos:kraken-pod-scenarios] 	"output_data": {
[chaos:kraken-pod-scenarios] 		"pods": {
[chaos:kraken-pod-scenarios] 			"1723732014361533777": {
[chaos:kraken-pod-scenarios] 				"namespace": "runner-keycloak",
[chaos:kraken-pod-scenarios] 				"name": "infinispan-router-766c85c469-qd97c",
[chaos:kraken-pod-scenarios] 				"creation_timestamp": "2024-08-15 13:17:01+00:00"
[chaos:kraken-pod-scenarios] 			}
[chaos:kraken-pod-scenarios] 		}
[chaos:kraken-pod-scenarios] 	}
[chaos:kraken-pod-scenarios] }
[chaos:kraken-pod-scenarios]
[chaos:kraken-pod-scenarios] 2024-08-15 14:32:56,642 [INFO] {
[chaos:kraken-pod-scenarios] 	"output_id": "error",
[chaos:kraken-pod-scenarios] 	"output_data": {
[chaos:kraken-pod-scenarios] 		"error": "timeout while waiting for pods to come up"
[chaos:kraken-pod-scenarios] 	}
[chaos:kraken-pod-scenarios] }
[chaos:kraken-pod-scenarios]
[chaos:kraken-pod-scenarios] 2024-08-15 14:32:56,643 [ERROR] scenario: scenarios/pod_scenario.yaml failed with exception: <class 'Exception'> file: /root/kraken/kraken/plugins/__init__.py line: 247
[chaos:kraken-pod-scenarios] 2024-08-15 14:32:56,644 [INFO]
[chaos:kraken-pod-scenarios] 2024-08-15 14:33:08,219 [INFO] Telemetry data:
[chaos:kraken-pod-scenarios] {
[chaos:kraken-pod-scenarios]     "scenarios": [
[chaos:kraken-pod-scenarios]         {
[chaos:kraken-pod-scenarios]             "startTimeStamp": 1723732014,
[chaos:kraken-pod-scenarios]             "endTimeStamp": 1723732376.6440089,
[chaos:kraken-pod-scenarios]             "scenario": "scenarios/pod_scenario.yaml",
[chaos:kraken-pod-scenarios]             "exitStatus": 1,
[chaos:kraken-pod-scenarios]             "parametersBase64": "",
[chaos:kraken-pod-scenarios]             "parameters": [
[chaos:kraken-pod-scenarios]                 {
[chaos:kraken-pod-scenarios]                     "config": {
[chaos:kraken-pod-scenarios]                         "kill": 1,
[chaos:kraken-pod-scenarios]                         "label_selector": "app=infinispan-router-pod,clusterName=infinispan",
[chaos:kraken-pod-scenarios]                         "namespace_pattern": "runner-keycloak",
[chaos:kraken-pod-scenarios]                         "timeout": 180
[chaos:kraken-pod-scenarios]                     },
[chaos:kraken-pod-scenarios]                     "id": "kill-pods"
[chaos:kraken-pod-scenarios]                 },
[chaos:kraken-pod-scenarios]                 {
[chaos:kraken-pod-scenarios]                     "config": {
[chaos:kraken-pod-scenarios]                         "count": 3,
[chaos:kraken-pod-scenarios]                         "label_selector": "app=infinispan-router-pod,clusterName=infinispan",
[chaos:kraken-pod-scenarios]                         "namespace_pattern": "runner-keycloak",
[chaos:kraken-pod-scenarios]                         "timeout": 360
[chaos:kraken-pod-scenarios]                     },
[chaos:kraken-pod-scenarios]                     "id": "wait-for-pods"
[chaos:kraken-pod-scenarios]                 }
[chaos:kraken-pod-scenarios]             ]
[chaos:kraken-pod-scenarios]         }
[chaos:kraken-pod-scenarios]     ],
[chaos:kraken-pod-scenarios]     "node_infos": [
[chaos:kraken-pod-scenarios]         {
[chaos:kraken-pod-scenarios]             "taints": [],
[chaos:kraken-pod-scenarios]             "instance_type": "unknown",
[chaos:kraken-pod-scenarios]             "node_type": "worker",
[chaos:kraken-pod-scenarios]             "name": "ip-10-0-12-12.ec2.internal",
[chaos:kraken-pod-scenarios]             "architecture": "amd64",
[chaos:kraken-pod-scenarios]             "kernel_version": "5.14.0-284.73.1.el9_2.x86_64",
[chaos:kraken-pod-scenarios]             "kubelet_version": "v1.28.11+add48d0",
[chaos:kraken-pod-scenarios]             "os_version": "Red Hat Enterprise Linux CoreOS 415.92.202407031156-0 (Plow)"
[chaos:kraken-pod-scenarios]         },
[chaos:kraken-pod-scenarios]         {
[chaos:kraken-pod-scenarios]             "taints": [],
[chaos:kraken-pod-scenarios]             "instance_type": "unknown",
[chaos:kraken-pod-scenarios]             "node_type": "worker",
[chaos:kraken-pod-scenarios]             "name": "ip-10-0-12-13.ec2.internal",
[chaos:kraken-pod-scenarios]             "architecture": "amd64",
[chaos:kraken-pod-scenarios]             "kernel_version": "5.14.0-284.73.1.el9_2.x86_64",
[chaos:kraken-pod-scenarios]             "kubelet_version": "v1.28.11+add48d0",
[chaos:kraken-pod-scenarios]             "os_version": "Red Hat Enterprise Linux CoreOS 415.92.202407031156-0 (Plow)"
[chaos:kraken-pod-scenarios]         },
[chaos:kraken-pod-scenarios]         {
[chaos:kraken-pod-scenarios]             "taints": [],
[chaos:kraken-pod-scenarios]             "instance_type": "unknown",
[chaos:kraken-pod-scenarios]             "node_type": "worker",
[chaos:kraken-pod-scenarios]             "name": "ip-10-0-12-4.ec2.internal",
[chaos:kraken-pod-scenarios]             "architecture": "amd64",
[chaos:kraken-pod-scenarios]             "kernel_version": "5.14.0-284.73.1.el9_2.x86_64",
[chaos:kraken-pod-scenarios]             "kubelet_version": "v1.28.11+add48d0",
[chaos:kraken-pod-scenarios]             "os_version": "Red Hat Enterprise Linux CoreOS 415.92.202407031156-0 (Plow)"
[chaos:kraken-pod-scenarios]         },
[chaos:kraken-pod-scenarios]         {
[chaos:kraken-pod-scenarios]             "taints": [],
[chaos:kraken-pod-scenarios]             "instance_type": "unknown",
[chaos:kraken-pod-scenarios]             "node_type": "worker",
[chaos:kraken-pod-scenarios]             "name": "ip-10-0-12-5.ec2.internal",
[chaos:kraken-pod-scenarios]             "architecture": "amd64",
[chaos:kraken-pod-scenarios]             "kernel_version": "5.14.0-284.73.1.el9_2.x86_64",
[chaos:kraken-pod-scenarios]             "kubelet_version": "v1.28.11+add48d0",
[chaos:kraken-pod-scenarios]             "os_version": "Red Hat Enterprise Linux CoreOS 415.92.202407031156-0 (Plow)"
[chaos:kraken-pod-scenarios]         },
[chaos:kraken-pod-scenarios]         {
[chaos:kraken-pod-scenarios]             "taints": [],
[chaos:kraken-pod-scenarios]             "instance_type": "unknown",
[chaos:kraken-pod-scenarios]             "node_type": "worker",
[chaos:kraken-pod-scenarios]             "name": "ip-10-0-12-7.ec2.internal",
[chaos:kraken-pod-scenarios]             "architecture": "amd64",
[chaos:kraken-pod-scenarios]             "kernel_version": "5.14.0-284.73.1.el9_2.x86_64",
[chaos:kraken-pod-scenarios]             "kubelet_version": "v1.28.11+add48d0",
[chaos:kraken-pod-scenarios]             "os_version": "Red Hat Enterprise Linux CoreOS 415.92.202407031156-0 (Plow)"
[chaos:kraken-pod-scenarios]         }
[chaos:kraken-pod-scenarios]     ],
[chaos:kraken-pod-scenarios]     "kubernetes_objects_count": {
[chaos:kraken-pod-scenarios]         "ConfigMap": 313,
[chaos:kraken-pod-scenarios]         "Pod": 156,
[chaos:kraken-pod-scenarios]         "Secret": 932,
[chaos:kraken-pod-scenarios]         "Deployment": 38,
[chaos:kraken-pod-scenarios]         "Route": 14,
[chaos:kraken-pod-scenarios]         "Build": 1
[chaos:kraken-pod-scenarios]     },
[chaos:kraken-pod-scenarios]     "network_plugins": [
[chaos:kraken-pod-scenarios]         "OVNKubernetes"
[chaos:kraken-pod-scenarios]     ],
[chaos:kraken-pod-scenarios]     "node_count": 5,
[chaos:kraken-pod-scenarios]     "cloud_infrastructure": "AWS",
[chaos:kraken-pod-scenarios]     "run_uuid": "44039d70-0f8b-4c30-a697-ab93a3c357db"
[chaos:kraken-pod-scenarios] }
[chaos:kraken-pod-scenarios] 2024-08-15 14:33:08,220 [INFO] telemetry collection disabled, skipping.
[chaos:kraken-pod-scenarios] 2024-08-15 14:33:08,220 [ERROR] Post scenarios are still failing at the end of all iterations
[chaos:kraken-pod-scenarios]  _              _
[chaos:kraken-pod-scenarios] | | ___ __ __ _| | _____ _ __
[chaos:kraken-pod-scenarios] | |/ / '__/ _` | |/ / _ \ '_ \
[chaos:kraken-pod-scenarios] |   <| | | (_| |   <  __/ | | |
[chaos:kraken-pod-scenarios] |_|\_\_|  \__,_|_|\_\___|_| |_|
[chaos:kraken-pod-scenarios]
[chaos:kraken-pod-scenarios]
task: Failed to run task "chaos:kill-gossip-router": exit status 1
```

**Comment by kami619** [comment]
Cluster failure script within `kc-failover.sh` works functionally with some exceptions and manual interventions.

The cluster objects for both Keycloak and external Infinispan get deleted, however the command `FAILOVER_MODE=CLUSTER_FAIL DOMAIN=a0ebba97687f87f44.dualstack.awsglobalaccelerator.com ./kc-failover.sh` fails to complete the lifecycle as it gets stuck on the `activeClusterDown` function execution, details in `DEBUG Log1`.

However, the cluster is set in the desired state, and all the pods are deleted from Keycloak and Infinispan.


DEBUG Log1:
```
+ activeClusterDown a0ebba97687f87f44.dualstack.awsglobalaccelerator.com
+ DOMAIN=a0ebba97687f87f44.dualstack.awsglobalaccelerator.com
++ dig +short client.a0ebba97687f87f44.dualstack.awsglobalaccelerator.com
++ sort
+ CLIENT_IPS=
++ dig +short primary.a0ebba97687f87f44.dualstack.awsglobalaccelerator.com
++ sort
+ PRIMARY_IPS=
++ dig +short backup.a0ebba97687f87f44.dualstack.awsglobalaccelerator.com
++ sort
+ BACKUP_IPS=
+ [[ '' == '' ]]
+ [[ '' != '' ]]
+ return
+ sleep 0.1
```

And coming to the recovery command `RECOVERY_MODE=ACTIVE DOMAIN=a0ebba97687f87f44.dualstack.awsglobalaccelerator.com ./kc-failover.sh` the recovery function exists prematurely unable to find `statefulsets.apps "infinispan" not found`. And as well sometimes there seems to be a race condition between the Keycloak and Infinispan operators, causing a lag between when the Infinispan pods come up and when the Keycloak pods come up, which results in a `work` cache not available on start-up message from Keycloak, but it resolves eventually on its own when all the needed pods come up.


DEBUG Log2:
```
INFO:2024-08-16-13:26:50-EDT Running Recovery scenario - ACTIVE
+ cat
+ kubectl -n runner-keycloak apply -f -
route.route.openshift.io/aws-health-route unchanged
+ kubectl -n openshift-operators scale --replicas=1 deployment/infinispan-operator-controller-manager
deployment.apps/infinispan-operator-controller-manager scaled
+ kubectl -n runner-keycloak scale --replicas=1 deployment/keycloak-operator
deployment.apps/keycloak-operator scaled
+ kubectl -n runner-keycloak rollout status --watch --timeout=600s statefulset/infinispan
Error from server (NotFound): statefulsets.apps "infinispan" not found
```


Full log:
```
> FAILOVER_MODE=CLUSTER_FAIL DOMAIN=a0ebba97687f87f44.dualstack.awsglobalaccelerator.com ./kc-failover.sh
INFO:2024-08-16-11:24:13-EDT Entering Failover mode, with an initial delay of 60 seconds
INFO:2024-08-16-11:25:13-EDT Running Failover scenario - CLUSTER_FAIL
deployment.apps/infinispan-operator-controller-manager scaled
deployment "infinispan-operator-controller-manager" successfully rolled out
deployment.apps/keycloak-operator scaled
deployment "keycloak-operator" successfully rolled out
Warning: Immediate deletion does not wait for confirmation that the running resource has been terminated. The resource may continue to run on the cluster indefinitely.
pod "infinispan-0" force deleted
pod "infinispan-1" force deleted
pod "infinispan-2" force deleted
pod "infinispan-router-766c85c469-gf5cf" force deleted
pod "keycloak-0" force deleted
pod "keycloak-1" force deleted
pod "keycloak-2" force deleted
pod "keycloak-operator-5f94d75864-f5tqk" force deleted
pod "keycloak-with-aws-jdbc-wrapper-1-build" force deleted
statefulset.apps "infinispan" deleted
statefulset.apps "keycloak" deleted
^C
> RECOVERY_MODE=ACTIVE DOMAIN=a0ebba97687f87f44.dualstack.awsglobalaccelerator.com ./kc-failover.sh
INFO:2024-08-16-11:30:20-EDT Running Recovery scenario - ACTIVE
route.route.openshift.io/aws-health-route created
deployment.apps/infinispan-operator-controller-manager scaled
deployment.apps/keycloak-operator scaled
Error from server (NotFound): statefulsets.apps "infinispan" not found

```

**Comment by kami619** [comment]
Gossip router failure and recovery scenario works as expected.

```
> FAILOVER_MODE=GOSSIP_ROUTER_FAIL DOMAIN=a0ebba97687f87f44.dualstack.awsglobalaccelerator.com ./kc-failover.sh
INFO:2024-08-16-13:30:54-EDT Entering Failover mode, with an initial delay of 60 seconds
INFO:2024-08-16-13:31:54-EDT Running Failover scenario - GOSSIP_ROUTER_FAIL
deployment.apps/infinispan-operator-controller-manager scaled
deployment "infinispan-operator-controller-manager" successfully rolled out
Warning: Immediate deletion does not wait for confirmation that the running resource has been terminated. The resource may continue to run on the cluster indefinitely.
pod "infinispan-router-766c85c469-jtf8z" force deleted
deployment.apps "infinispan-router" deleted
> RECOVERY_MODE=ACTIVE DOMAIN=a0ebba97687f87f44.dualstack.awsglobalaccelerator.com ./kc-failover.sh
INFO:2024-08-16-13:32:24-EDT Running Recovery scenario - ACTIVE
route.route.openshift.io/aws-health-route unchanged
deployment.apps/infinispan-operator-controller-manager scaled
deployment.apps/keycloak-operator scaled
statefulset rolling update complete 3 pods at revision infinispan-694bb5cc4d...
partitioned roll out complete: 3 new pods have been updated...
```

**Comment by ahus1** [comment]
Thank you for this work!

Next step: Create create follow-up task and then close this issue.

**Comment by kami619** [comment]
I have logged the issues and closing this issue now.
